name: Publish `eda_toolkit` Python Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # Check out the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Setup with Python 3.x

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine  # Use build instead of setup.py

    - name: List files in the directory (debug step)
      run: ls -la

    - name: Build the package
      run: python -m build  # Build using pyproject.toml

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload dist/*
